#ifndef _CRYPTO_CONFIG_H
#define _CRYPTO_CONFIG_H

#define SHA256_SUPPORT ENABLED
#define GMAC_SUPPORT ENABLED
#define AES_SUPPORT ENABLED
#define GCM_SUPPORT ENABLED
#define EC_SUPPORT ENABLED
#define ECDH_SUPPORT ENABLED
#define X25519_SUPPORT ENABLED

#endif  // _CRYPTO_CONFIG_H
